wip: working on add 供品.
meathill/sf-aigc-hackathon-2023 pull request #15
Opened 2023-04-01 03:07 UTC by bambooom

2023-04-02 13:36 UTC, meathill requested changes

2023-04-02 13:36 UTC, meathill commented on packages/app/src/store/history.ts
> +  const totalScore = ref<number>(localStorage.getItem(TOTAL_SCORE)
这个不能通过 history 叠加计算么？我原本期待每天拜佛的时候把功德点放到 history 里。

2023-04-02 13:36 UTC, meathill commented on packages/app/src/components/gongpin-table.vue
> +const historyStore = useHistoryStore();
import 和常量之间要留有一个空行。

2023-04-02 13:36 UTC, meathill commented on packages/app/src/components/gongpin-table.vue
> +const getOfferImg = (name: string) => {
少用这种 `const foo = function` 的形式，可能导致函数没有变量提升的问题。

2023-04-02 13:36 UTC, meathill commented on packages/app/src/components/gongpin-table.vue
> +  historyStore.addScore(-len);
getter 里面不要有副作用。

2023-04-02 13:36 UTC, meathill commented on packages/app/src/components/gongpin-table.vue
> +      img(v-for="item in selectedGongpin"
换行。

2023-04-03 04:49 UTC, bambooom commented on packages/app/src/store/history.ts
> +  const totalScore = ref<number>(localStorage.getItem(TOTAL_SCORE)
主要它不是只加不减的，你添加供品和香火都要减掉功缘点，这部分好像不在 history 里存放吧？

2023-04-03 06:25 UTC, meathill commented on packages/app/src/store/history.ts
> +  const totalScore = ref<number>(localStorage.getItem(TOTAL_SCORE)
目前我们最好先保存历史细节，因为总量很快能算出来，将来需要再做一个总计好了。

2023-04-03 08:11 UTC, meathill approved these changes

2023-04-03 08:12 UTC, merged