tts demo init
meathill/sf-aigc-hackathon-2023 pull request #6
Opened 2023-03-09 11:55 UTC by dzlkuboy

2023-03-09 13:18 UTC, meathill requested changes
1. 配置编辑器，给文件最后加上空行
2. 这是个 API 接口，不需要网页相关。你可以在本地开发，但不需要提交
3. 尽量用 ts
4. 对自己的代码要有所掌控，每一行都要能解释清楚
5. mp3 不要提交

2023-03-09 13:18 UTC, meathill commented on .gitignore
> +
1. 一般一个换行就够
2. 如果是依赖换行的语言，可以适当用多个

2023-03-09 13:18 UTC, meathill commented on config.js
> +const params = {
用 `enum` + 默认参数，不要这样写。

2023-03-09 13:18 UTC, meathill commented on config.js
> +const OUTPUT_FORMAT = FORMATS[params.AUE] || FORMATS[3];
不需要写没帮助的代码……

2023-03-09 13:18 UTC, meathill commented on index.js
> +const hasPermission = (result) => {
尽量少用 `const func = () => {}`，你可以想想它跟 `function func() {}` 有什么区别。

2023-03-09 13:18 UTC, meathill commented on index.js
> +  const hasToken = Object.keys(result).includes("access_token");
这是什么鬼？本来是 O(1)，你这样一来不仅变成 O(logN) 而且多算一步。

2023-03-09 13:18 UTC, meathill commented on index.js
> +    return result["access_token"];
为什么 `hasPermission()` 会返回 `access_token`？

2023-03-09 13:18 UTC, meathill commented on index.js
> +      return;
这个错误不处理么？

2023-03-09 13:18 UTC, meathill commented on index.js
> +  getTokenParams,
变量不要用动宾短语。

2023-03-09 13:18 UTC, meathill commented on index.js
> +  queryTexToSpeech: (params1) => {
为什么有个 `1`？

2023-03-09 13:18 UTC, meathill commented on index.js
> +      url: params.TTS_URL + `?${getSortParams(params1)}`,
为什么不用 `params` 参数？

2023-03-09 13:18 UTC, meathill commented on index.js
> +  } catch (err) {}
不 `catch` 你 `try` 什么？

2023-03-09 13:18 UTC, meathill commented on index.js
> +  const tex = encodeURI(encodeURI(TEXT));
为什么 encode 两次？

2023-03-09 13:18 UTC, meathill commented on index.js
> +  };
为什么不直接用小写？这里可以少重复一遍

2023-03-09 13:18 UTC, meathill commented on index.js
> +    fs.writeFileSync(filePath, result.data, {
不要用 `XXXsync`，直接用 `fs/promises` 里的版本。

2023-03-09 13:18 UTC, meathill commented on index.js
> +  const result = await texToSpeech(token);
这个函数有用么？为什么 `init params` 里会有发起请求的功能？

2023-03-09 13:18 UTC, meathill commented on package.json
> +  "name": "nodejs",
名字写清楚。

2023-03-09 13:18 UTC, meathill commented on utils.js
> +function getMacAddress() {
需要用到 mac 地址么？

2023-03-09 13:18 UTC, meathill commented on utils.js
> +const getSortParams = (params) => {
用 `URLSearchParams`

2023-03-10 14:10 UTC, dzlkuboy commented on index.js
> +  const tex = encodeURI(encodeURI(TEXT));
百度云文档提供的方法是推荐文本encode两次

2023-03-10 14:11 UTC, dzlkuboy commented on utils.js
> +function getMacAddress() {
需要的, 百度云文档提供的uuid, 也就是mac地址

2023-03-11 08:00 UTC, meathill reviewed
1. 不要提交不必要的文件。提了 PR 之后自己要看上一两遍再提交给 reviewer，要尊重 reviewer 的时间与精力。
2. 之前提的问题都要改。如果有一些不打算改或者不知道怎么改，要先沟通。不要纠缠在重复问题里。尊重 reviewer 的时间与精力。

2023-03-11 08:13 UTC, dzlkuboy commented
> 1. 不要提交不必要的文件。提了 PR 之后自己要看上一两遍再提交给 reviewer，要尊重 reviewer 的时间与精力。
> 2. 之前提的问题都要改。如果有一些不打算改或者不知道怎么改，要先沟通。不要纠缠在重复问题里。尊重 reviewer 的时间与精力。

2023-03-11 08:13 UTC, closed without merging

2023-03-14 05:35 UTC, dzlkuboy commented on config.js
> +const params = {
用 enum + 默认参数，不要这样写。

能举个例子吗, 这样写的坏处在哪可以告知不